---
#- name: "Add Node"
#  become: true
#  shell: |
#      curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
- name: "Install Node"
  become: true
  apt:
      name: ["nodejs", "npm"]
      state: present
      update_cache: yes

- name: "Install PM2"
  command: npm install pm2 -g
  #npm:
  #    name: pm2
  #    global: yes