---
- name: Create directory
  become: true
  file:
    path: ~/backend_app
    state: directory

- name: List files and folder in home directory
  shell: 'ls -l ~/'
  register: command_output
- debug:
    var: command_output.stdout_lines

- name: Install tar and gzip
  become: true
  shell: apt install -y tar gzip

- name: install zip and unzip
  become: true
  become_method: sudo
  apt: name={{ item }} state=present
  with_items:
  - zip
  - unzip

- name: Extract zipped artifact into the EC2 instance
  become: true
  #shell: |    
  #  tar -xvzf artifact.tar.gz -C backend_app/
  unarchive:
    src: "~/project/artifact.tar.gz"
    dest: "~/backend_app/"
  
- name: Install dependencies
  shell: |
    cd ~/backend_app
    npm install --legacy-peer-deps

- name: Start the app
  shell: |
    cd ~/backend_app/dist
    pm2 stop default
    pm2 start main.js

#- name: Configure pm2 to start as service
#  become: true
#  shell: |
#      env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu