---
- name: Create directory
  become: yes
  file:
    path: ~/backend_app
    state: directory

- name: Extract zipped artifact into the EC2
  become: yes
  unarchive:
    src: artifact.tar.gz
    dest: "~/backend_app"

- name: Install dependencies
  shell: |
    cd ~/backend_app
    npm install

- name: Start the app
  shell: |
    cd ~/backend_app/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node

- name: print message
  debug:
      msg: "{{ execute_node.stdout_lines }}"

- name: Configure pm2 to start as service
  become: true
  shell: |
      env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu