---
- name: Install dependencies
  npm:
    path: /backend
    state: latest

- name: Extract zipped artifact into the EC2 and start the app
  raw: |
    npm install
    pm2 stop default
    pm2 start npm -- start