---
- name: Create directory
  become: yes
  npm:
    path: /backend_app
    state: directory

- name: Extract zipped artifact into the EC2
  unarchive:
    src: ~/project/.circleci/artifact.tar.gz
    dest: "~/backend_app"

- name: Install dependencies
  shell: |
    cd ~/backend_app
    npm install

- name: Start the app
  shell: |
    cd ~/backend_app/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node