---
- name: Install dependencies
  become: yes
  npm:
    path: /backend
    state: directory

- name: Extract zipped artifact into the EC2
  unarchive:
    src: ~/.circleci/project/artifact.tar.gz
    dest: "~/backend"

- name: Install dependencies
  shell: |
    cd ~/backend
    npm install

- name: Start the app
  shell: |
    cd ~/backend_app/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node