---
- name: Install dependencies
  become: yes
  npm:
    path: /backend
    state: latest

- name: Extract zipped artifact into the EC2 and start the app
  become: yes
  shell: |
    npm install
    ls
    tar -xf artifact.tar.gz
    pm2 stop default
    pm2 start npm -- start